name: test1
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - pandas
  - scikit-learn
  - matplotlib
  - ipython
  - ipykernel
  - seaborn
  - numpy[version='<2']
  - kagglehub
  - imbalanced-learn
  - pip:
      - optuna==4.5.0
      - alembic==1.17.0
      - keras==3.12.0
      - tensorflow==2.20.0
